services:
  - type: web
    name: tg-bot-webhook
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind :$PORT --workers 1 --timeout 120 app:app
    envVars:
      - key: BOT_TOKEN
        value: 7846744690:AAFtYLy4DdsjOtjhmMVnL1knokSO8raJPnY
      - key: DB_HOST
        value: ep-cool-darkness-123456.us-east-2.aws.neon.tech
      - key: DB_NAME
        value: neondb
      - key: DB_USER
        value: nikita_zhilin
      - key: DB_PASSWORD
        value: ваш_пароль
      - key: DB_PORT
        value: "5432"
      - key: RENDER_SERVICE_NAME
        value: tg-bot-webhook