services:
  - type: web
    name: tg-bot-napominalka
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host=0.0.0.0 --port=$PORT
    envVars:
      - key: BOT_TOKEN
        value: 7846744690:AAFtYLy4DdsjOtjhmMVnL1knokSO8raJPnY
      - key: RENDER_SERVICE_NAME
        value: tg-bot-napominalka.onrender.com
      - key: DB_HOST
        value: ep-purple-wave-a9bx68xy-pooler.gwc.azure.neon.tech
      - key: DB_NAME
        value: bot_reminder_db
      - key: DB_USER
        value: bot_reminder_db_owner
      - key: DB_PASSWORD
        value: npg_6QLicFIXOW2J
      - key: DB_PORT
        value: "5432"
      - key: RENDER_EXTERNAL_HOSTNAME
        value: tg-bot-napominalka.onrender.com
      - key: ADMIN_IDS
        value: 372690348


