services:
  - type: web
    name: tg-bot-napominalka
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind :$PORT --workers 4 --timeout 120 app:app
    envVars:
      - key: BOT_TOKEN
        value: 7846744690:AAFtYLy4DdsjOtjhmMVnL1knokSO8raJPnY
      - key: RENDER_SERVICE_NAME
        value: tg-bot-napominalka.onrender.com
      - key: DB_HOST
        value: ep-purple-wave-a9bx68xy-pooler.gwc.azure.neon.tech
      - key: DB_NAME
        value: бот напоминалка
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_QpsFjD8Goc2i
      - key: DB_PORT
        value: "5432"